### ISSUE TITLE
NanoPI M3 + OV5640(CAM500b)

### ISSUE THREAD

**Issue by denevs** [avafinger/ov5640#2]
Hello, im trying your code on NanoPI M3 with CAM500B. First git clone -b NanoPi_M2_M3 . I took 2 files. I ill try to make install 'ov5640.c' and saw that there are no linux/init.h(etc) I fix it with downloading kernel for M3 https://github.com/friendlyarm/linux-3.4.y the i try (gcc -c ov5640.c -o ov5640.o -I /home/fa/linux-3.4.y/include/) some mistakes was in /asm libs, i renamed all to /asm-generic/ ,but some files doesnt exist(processor.h) I commeted it. After that compiling done, but nothing appears. Some errors presented like (/home/fa/linux-3.4.y/include/linux/workqueue.h:304:1: error: old-style parameter declarations in prototyped function definition
 __alloc_workqueue_key(const char *fmt, unsigned int flags, int max_active,)
Is there any way to fix installation or writing some man for newbees, how to install your ov5640c?

**Comment by avafinger** [comment]
Hi denevs,
I haven't touched the driver for a long time, actually it was just a start, there is no improvement.
The driver must be compiled in the kernel tree, that what i used to do. There is a way to build as a module from userspace but can't remember how. My M3 works with CAM500A. I will revisit it and build with latest gcc 7.1 and update when possible.

Sorry for the confusion.

**Comment by denevs** [comment]
Hello,thank you for a quick answer. It will be great
